---
title: "Ecosystems Exploration"
author: "Jess"
date: '2022-10-27'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(tidyverse)
library(knitr)
library(pander)
library(esquisse)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir ="~/DTSC/Manufacturing_Projects/csv/Ecosystems")
title<-theme(plot.title = element_text(face="bold", hjust= 0.5))
th=theme_bw(base_size=10)+theme(strip.background= element_rect(fill="white"))
```

```{r}
terrestrial_hab <- read.csv("Terrestrial_significant_habitats.csv")
hab_connectivity <- read.csv("Habitat_connectivity.csv")
aq.bio <- read.csv("Aquatic_biodiversity.csv")
terr.bio <- read.csv("Terrestrial_biodiversity.csv")
aquatic_hab <- read.csv("Aquatic_significant_habitats.csv")
```


```{r}
#count of each rank
terr_rank <- terrestrial_hab %>% 
  count(TerrHabRank) %>% 
  arrange(TerrHabRank)

#count of each rank per Eco_Name region
terr_summary<- terrestrial_hab %>% 
  group_by(Eco_Name) %>% 
  count(TerrHabRank)

#count of hexes per Eco_Name region
regions<- terrestrial_hab %>% 
  group_by(Eco_Name) %>% 
  count(Eco_Name)

#pander(terr_rank)
#pander(terr_summary)
#pander(regions)
```


```{r}
#new dataframe with Monarch info, Eco_Name region and count per rank for each factor.
monarch <- terrestrial_hab %>% 
  group_by(Eco_Name, Monarch) %>% 
  count(TerrHabRank)
#pander(monarch)

```

```{r}
ggplot(terrestrial_hab) +
 aes(x = TerrHabRank) +
 geom_histogram(bins = 30L, fill = "#5D89AE") +
 theme_bw() + labs(title= "Count of Terrestrial Sensitive Habitats by Rank", x = "Terrestrial Sensitive Habitat Rank", y= "Count of Hexes") + title
```


```{r}
#esquisser(terrestrial_hab)

ggplot(terrestrial_hab) +
 aes(x = TerrHabRank) +
 geom_histogram(bins = 30L, fill = "#5D89AE") +
 theme_bw() +
 facet_wrap(vars(Eco_Name)) +  labs(title= "Terrestrial Sensitive Habitats Count by Eco-Region", x = "Terrestrial Sensitive Habitat Rank", y= "Count of Terrestrial Hexes") + title
```

```{r}

#Background plot to show the different Eco Regions. 
ggplot(terrestrial_hab) +
 aes(x = Eco_Name, y = TerrHabRank) +
 geom_boxplot(fill = "#5D89AE") +
 theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  + labs(title= "Terrestrial Sensitive Habitats by Eco-Region", x = "Eco-Region", y= "Terrestrial Sensitive Habitat Rank") + title
```
# Central Valley Coast Ranges, Northern California Coast, Northern California Interior Coast Ranges
# Klamath Mountains, Northern California Coast Ranges, Southern Cascades

```{r}
terr.anova.df <- terrestrial_hab %>% 
  group_by(Eco_Name) %>% 
  count(TerrHabRank)

RCBDmodel <- lm(formula = n ~ TerrHabRank + Eco_Name,
                data = terr.anova.df)

anova(object = RCBDmodel)
```

```{r}
coastal.ranges <- terrestrial_hab %>% 
  subset(Eco_Name == c("Central Valley Coast Ranges", "Northern California Coast", "Northern California Interior Coast Ranges")) %>% 
  group_by(Eco_Name) %>% 
  count(TerrHabRank)

coastal.model <- lm(formula = n ~ TerrHabRank + Eco_Name,
                data = coastal.ranges)

anova(coastal.model)
```

```{r}
mountain.ranges <- terrestrial_hab %>% 
  subset(Eco_Name == c("Klamath Mountains", "Northern California Coast Ranges", "Southern Cascades")) %>%
  group_by(Eco_Name) %>% 
  count(TerrHabRank)

mountain.model <- lm(formula = n ~ TerrHabRank + Eco_Name,
                data = mountain.ranges)

anova(mountain.model)
```



```{r}
linear.model1 <- lm(formula = n ~ TerrHabRank, data = monarch)
anova(object = linear.model1)
```


```{r}
#count of each rank
aqua_rank <- aquatic_hab %>% 
  count(AqHabRank) %>% 
  arrange(AqHabRank)

#esquisser(aquatic_hab)


ggplot(aquatic_hab) +
 aes(x = AqHabRank, fill = Riparian) +
 geom_histogram(bins = 30L) +
 scale_fill_hue(direction = 1) +
 theme_minimal()+ labs(title= "Count of Aquatic Sensitive Habitats by Rank", x = "Aquatic Sensitive Habitat Rank", y= "Count of HUC 12") + title


ggplot(aquatic_hab) +
 aes(x = AqHabRank, fill = Lakes) +
 geom_histogram(bins = 30L) +
 scale_fill_hue(direction = 1) +
 theme_minimal()+ labs(title= "Count of Aquatic Sensitive Habitats by Rank", x = "Aquatic Sensitive Habitat Rank", y= "Count of HUC 12") + title


ggplot(aquatic_hab) +
 aes(x = AqHabRank) +
 geom_histogram(bins = 30L, fill = "#5D89AE") +
 theme_bw() + labs(title= "Count of Aquatic Sensitive Habitats by Rank", x = "Aquatic Sensitive Habitat Rank", y= "Count of HUC 12") + title

```

```{r}

```


