---
title: "Map Boxer"
author: "Jess"
date: '2022-12-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(knitr)
opts_knit$set(root.dir="~/DTSC/Manufacturing_Projects/csv/Ecosystems")
rm(list=ls())
library(tidyverse)
library(sf)
library(ggplot2)
library(plotly)
library(dplyr)
library(rgdal)
library(ggspatial)
library(viridis)
library(leaflet)
library(shiny)
```

```{r}
#This reads in the .gdb and shows the layers so you know which layer to read in. In this case, it doesn't matter. But some other .gdb will have multiple layers.
aquatic.gdb <- st_read("ds2756.gdb")
st_layers("ds2756.gdb")

aquatic_lyr <- sf::st_read(dsn = "ds2756.gdb", layer = "ds2756")

terrestrial.gdb <- st_read("ds2721.gdb")
st_layers("ds2721.gdb")

terrestrial_lyr <- sf::st_read(dsn = "ds2721.gdb", layer = "ds2721")

#clear these out of your environment to take up less space
rm(terrestrial.gdb)
rm(aquatic.gdb)
```

```{r}
#Read in the census tracts and the DACs from sb535. Create a subset shp of the sb535 DACs.
tracts <- st_read("CES4_Final_Shapefile.shp")
sb535_tracts <- read.csv("Sb535.tracts.csv")
subset_sb535 <- tracts %>% 
  filter(Tract %in% sb535_tracts$Census.Tract)
```

```{r}
#this reads in the data set for tribal land within the sb535 gdb.
dacs <- st_read("SB535DACgdb_F_2022.gdb")
#this shows us the layers with their projections of the dataset
st_layers("SB535DACgdb_F_2022.gdb")

#create a spatial layer for tribal boundaries
tribal<- sf::st_read(dsn = "SB535DACgdb_F_2022.gdb", layer = "SB535tribalboundaries2022")
```


```{r}
basemap <- leaflet() %>% 
  setView(lat = 36.778259, lng = -119.417931, zoom = 5) %>%
  addTiles()
```

https://rstudio.github.io/leaflet/showhide.html
https://rstudio-pubs-static.s3.amazonaws.com/307862_b8c8460272dc4a2a9023d033d5f3ec34.html
https://rstudio.github.io/leaflet/


```{r}
#This makes sure all of the datasets can speak with the leaflet basemap with the same projection and geometry. 
aquatic_lyr <- st_transform(aquatic_lyr, CRS("+proj=longlat +datum=WGS84"))
terrestrial_lyr <- st_transform(terrestrial_lyr, CRS("+proj=longlat +datum=WGS84"))
subset_sb535 <- st_transform(subset_sb535, CRS("+proj=longlat +datum=WGS84"))
tribal <- st_transform(tribal, CRS("+proj=longlat +datum=WGS84"))
```


```{r}
#set color palettes for maps.
aq5 <- colorNumeric("viridis", domain = aquatic_lyr$AqHabRank)
tr5 <- colorNumeric("magma", domain = aquatic_lyr$TerrHabRank)
tribe_col <- colorFactor("#de2d26", domain=tribal$GEOID)
dacs_col <- colorFactor("#006837", domain = subset_sb535$Tract)
```



```{r}
#labels for polygons
dac_label <- sprintf(
  "<h2>%s</h2>",
  subset_sb535$ApproxLoc) %>% 
  lapply(htmltools::HTML)

tribal_label <- sprintf(
  "<h2>%s</h2>",
  tribal$Name) %>% 
  lapply(htmltools::HTML)

```

```{r eval=FALSE, include=FALSE}
habitat_map <- basemap %>% 
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addTiles(group = aquatic_lyr$AqHabRank,"Aquatic Significant Habitat") %>% 
  addTiles(group = terrestrial_lyr$TerrHabRank, "Terrestrial Significant Habitat") %>% 
  addPolygons(data=aquatic_lyr, 
              fillColor= ~aq5(AqHabRank),
              fillOpacity =.7,
              color= NA,
              group = "Aquatic Significant Habitat") %>% 
  addPolygons(data=terrestrial_lyr,
              fillColor= ~tr5(TerrHabRank),
              fillOpacity =.7,
              color = NA,
              group = "Terrestrial Significant Habitat") %>% 
  addLegend(position = "bottomright", 
            pal = aq5, 
            title = "Aquatic Significant <br>Habitat Rank", 
            values = aquatic_lyr$AqHabRank, 
            group = "Aquatic Significant Habitat",
            opacity = 1) %>% 
  addLegend(position = "bottomright", 
            pal = tr5, 
            title = "Terrestrial Significant <br>Habitat Rank", 
            values = terrestrial_lyr$TerrHabRank, 
            group = "Terrestrial Significant Habitat",
            opacity = 1) %>% 
  addLayersControl(
    baseGroups = "Terrain",
    overlayGroups = c("Aquatic Significant Habitat", "Terrestrial Significant Habitat"),
    options = layersControlOptions(collapsed=FALSE)
  )
```


```{r eval=FALSE, include=FALSE}
map_535 <- basemap %>% 
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addTiles(group = subset_sb535$Tract, "SB 535 DACs") %>% 
  addTiles(group = tribal$GEOID, "Federally Recognized Tribes") %>% 
  addPolygons(data=tribal,
              fillColor= ~tribe_col(GEOID),
              fillOpacity = 0.9,
              color= "#252525",
              weight=1,
              group = "Federally Recognized Tribes",
              label = tribal_label,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addPolygons(data=subset_sb535,
              fillColor=~dacs_col(Tract),
              fillOpacity = 0.9,
              color = "#252525",
              weight =1,
              group = "SB 535 DACs",
              label = dac_label,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addLayersControl(
    baseGroups = "Terrain",
    overlayGroups = c("SB 535 DACs", "Federally Recognized Tribes"),
    options = layersControlOptions(collapsed=FALSE)
              )
```


```{r}
big_a_map <-  basemap %>% 
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addTiles(group = aquatic_lyr$AqHabRank,"Aquatic Significant Habitat") %>% 
  addTiles(group = terrestrial_lyr$TerrHabRank, "Terrestrial Significant Habitat") %>% 
  addTiles(group = subset_sb535$Tract, "SB 535 DACs") %>% 
  addTiles(group = tribal$GEOID, "Federally Recognized Tribes") %>% 
    addPolygons(data=aquatic_lyr, 
              fillColor= ~aq5(AqHabRank),
              fillOpacity =.7,
              color= NA,
              group = "Aquatic Significant Habitat") %>% 
  addPolygons(data=terrestrial_lyr,
              fillColor= ~tr5(TerrHabRank),
              fillOpacity =.7,
              color = NA,
              group = "Terrestrial Significant Habitat") %>% 
  addPolygons(data=tribal,
              fillColor= ~tribe_col(GEOID),
              fillOpacity = 0.9,
              color= "#252525",
              weight=1,
              group = "Federally Recognized Tribes",
              label = tribal_label,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addPolygons(data=subset_sb535,
              fillColor=~dacs_col(Tract),
              fillOpacity = 0.9,
              color = "#252525",
              weight =1,
              group = "SB 535 DACs",
              label = dac_label,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addLegend(position = "bottomright", 
            pal = aq5, 
            title = "Aquatic Significant <br>Habitat Rank", 
            values = aquatic_lyr$AqHabRank, 
            group = "Aquatic Significant Habitat",
            opacity = 1) %>% 
  addLegend(position = "bottomright", 
            pal = tr5, 
            title = "Terrestrial Significant <br>Habitat Rank", 
            values = terrestrial_lyr$TerrHabRank, 
            group = "Terrestrial Significant Habitat",
            opacity = 1) %>% 
  addLayersControl(
    baseGroups = "Terrain",
    overlayGroups = c("Aquatic Significant Habitat", "Terrestrial Significant Habitat", "SB 535 DACs", "Federally Recognized Tribes"),
    options = layersControlOptions(collapsed=FALSE)
  )
```

```{r}
big_a_map
```

```{r}

```


