---
title: "Exploration of Master Facility List"
author: "Jess"
date: '2022-09-14'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(stringr)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir ="~/DTSC/Manufacturing_Projects/Manufacturing-SCP/Data/Clean_Data")
rm(list = ls())
```

```{r}
master <- read_excel("facilities_shiny.xlsx")
naics_individual <- read.csv("naics_groups.csv")
naics_counted <- read.csv("naics_counted.csv") 
sic_counted <- read.csv("sic_counted.csv")
```



```{r}
#Group NAICS categories - take the first 3 digits from NAICS codes to see how many.
naics_individual$groups <- naics_individual$code %>% 
  str_sub(start = 1, end = 3)
  

naics_groups <- naics_individual %>% 
  filter(grepl("^31", code) | grepl("^32", code)| grepl("^33", code)) %>% 
  count(groups) %>% 
  arrange(desc(n))


title<-theme(plot.title = element_text(face="bold", hjust= 0.5))

ggplot(naics_groups) +
 aes(x = groups, y = n, fill = groups) +
 geom_col() +
 scale_fill_manual(values = c(`311` = "#F8766D", 
`312` = "#E98141", `313` = "#DA8C15", `314` = "#C69600", `315` = "#ACA000", `316` = "#93AA00", `321` = "#58B016", 
`322` = "#1DB62C", `323` = "#00BB4C", `324` = "#00BE75", `325` = "#00C19F", `326` = "#00BDBA", `327` = "#00BAD5", 
`331` = "#13B3E8", `332` = "#3AA7F3", `333` = "#619CFF", `334` = "#918BFD", `335` = "#C27AFB", `336` = "#E26EEF", 
`337` = "#F067D9", `339` = "#FF61C3")) +
 labs(x = "NAICS 3 Digit Group", y = "Count of Group", title = "NAICS Groups Count") +
 theme_minimal() + title + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme(legend.position = "none")
```


```{r}
#Group NAICS categories - take the first 3 digits from NAICS codes to see how many.
naics_individual$groups4 <- naics_individual$code %>% 
  str_sub(start = 1, end = 4)
  

naics_groups4 <- naics_individual %>% 
  filter(grepl("^31", code) | grepl("^32", code)| grepl("^33", code)) %>% 
  count(groups4) %>% 
  arrange(desc(n))

#esquisser(naics_groups4)

title<-theme(plot.title = element_text(face="bold", hjust= 0.5))
th=theme_bw(base_size=10)+theme(strip.background= element_rect(fill="white"))

ggplot(naics_groups4) +
 aes(x = groups4, y = n) +
 geom_col(fill = "#112446") +
 theme_minimal() + title + 
  labs(x = "NAICS 4 Digit Group", y = "Count", title = "NAICS Groups Count") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))





```

```{r}
naics_groups$groups
#write.csv(naics_groups, "~\\DTSC\\Manufacturing_Projects\\csv\\naics_3.csv", row.names=FALSE)
```

```{r}
#Group NAICS categories - take the first 3 digits from NAICS codes to see how many.
sic_counted$groups <- sic_counted$code %>% 
  str_sub(start = 1, end = 2)
  

sic_groups <- sic_counted %>% 
  filter(grepl("^20", code) | grepl("^21", code)| grepl("^22", code)| grepl("^23", code)| grepl("^24", code)| grepl("^25", code)| grepl("^26", code)| grepl("^27", code)| grepl("^28", code)| grepl("^29", code)| grepl("^30", code)| grepl("^31", code)| grepl("^32", code)| grepl("^33", code)| grepl("^34", code)| grepl("^35", code)| grepl("^36", code)| grepl("^37", code)| grepl("^38", code)| grepl("^39", code)) %>% 
  count(groups) %>% 
  arrange(desc(n))

#esquisser(sic_groups)


ggplot(sic_groups) +
  aes(x = groups, y = n, fill = groups) +
  geom_col() +
  scale_fill_hue(direction = 1) +
  labs(
    x = "SIC 2 Digit Groups",
    y = "Count of Group",
    title = "SIC Groups Count"
  ) +
  theme_minimal() + title + theme(axis.text.x = element_text(angle=45, hjust =1)) + theme(legend.position = "none")
```
```{r}
#write.csv(sic_groups, "~\\DTSC\\Manufacturing_Projects\\csv\\sic_3.csv", row.names=FALSE)
```

