---
title: "SIC_NAICS_Counting"
author: "Jess"
date: '2022-12-01'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(stringr)
library(readxl)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir ="~/DTSC/Manufacturing_Projects/Manufacturing-SCP/Data/Clean_Data")
rm(list = ls())
```


```{r}
master <- read_excel("facilities_shiny.xlsx")
```

```{r}
naics <- master %>% 
  count(NAICS_Code) %>% 
  arrange(desc(n))
```

```{r}
sic <- master %>% 
  count(SIC_Code) %>% 
  arrange(desc(n))
```

```{r}
SICs_needed <-  ifelse(master$NAICS_Code == "NA", master$SIC_Code, "")
```

```{r}
sic_separated <- str_split(SICs_needed,"\\,\\s" )
sic_sep <- mapply(function(id,code) data.frame(id,code), id= master$Program_ID, code= sic_separated,SIMPLIFY = FALSE)

sic_individual <- do.call(rbind,sic_sep)
sic_counted <- sic_individual %>% 
  count(code) %>% 
  arrange(desc(n))
```


```{r}
unique <- as.character(naics$NAICS_Code)
#unique <- paste0(unique, collapse=", ") #this gets rid of "the quotes, but we want this to count NAICS.
```

```{r}
naics_separated <- str_split(master$NAICS_Code,"\\,\\s" )
naics_sep <- mapply(function(id,code) data.frame(id,code), id= master$Program_ID, code= naics_separated,SIMPLIFY = FALSE)

head(naics_sep[[1]])
head(naics_separated)

naics_individual <- do.call(rbind,naics_sep)

naics_counted <- naics_individual %>% 
  count(code) %>% 
  arrange(desc(n))

```


```{r}
#write.csv(naics_individual, "~\\DTSC\\Manufacturing_Projects\\csv\\naics_groups.csv", row.names=FALSE)
#write.csv(naics_counted, "~\\DTSC\\Manufacturing_Projects\\csv\\naics_counted.csv", row.names=FALSE) 
#write.csv(sic_counted, "~\\DTSC\\Manufacturing_Projects\\csv\\sic_counted.csv", row.names=FALSE)
```
